"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['copylist.py']
DATA_FILES = ['copy_list1.txt', 'copy_list2.txt', 'copy_list3.txt', 'copy_list4.txt', 'copy_list5.txt']
OPTIONS = {
	'iconfile': 'copylist.icns',
	'plist': {
        'CFBundleName': "CopyList",
        'CFBundleDisplayName': "CopyList",
        'CFBundleGetInfoString': "CopyList",
        'CFBundleIdentifier': "com.metachris.osx.copylist",
        'CFBundleVersion': "0.1.0.5",
        'CFBundleShortVersionString': "0.1.0.5",
        'NSHumanReadableCopyright': u"Copyright 2019, Kim Jack, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
