"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['WebHoster.py']
DATA_FILES = ['webhoster.tpl', 'image_1.png', 'image_2.png', 'image_3.png', 'image_4.png', 'image_5.png', 'image_6.png', 'image_7.png', 'image_8.png', 'image_9.png', 'image_10.png', 'image_11.png', 'image_12.png', 'image_13.png', 'image_14.png', 'image_15.png', 'image_16.png', 'image_17.png', 'image_18.png', 'image_19.png', 'image_20.png']
# DATA_FILES = ['webhoster.tpl', '/static/image_1.png', '/static/image_2.png', '/static/image_3.png']
# DATA_FILES = ['webhoster.tpl', 'static/image_1.png', 'static/image_2.png', 'static/image_3.png', 'images/image_1.png', 'images/image_2.png', 'images/image_3.png']
OPTIONS = {
	'iconfile': 'webhoster.icns',
	'plist': {
        'CFBundleName': "WebHoster",
        'CFBundleDisplayName': "WebHoster",
        'CFBundleGetInfoString': "WebHoster",
        'CFBundleIdentifier': "com.metachris.osx.WebHoster",
        'CFBundleVersion': "0.1.0.0",
        'CFBundleShortVersionString': "0.1.0.0",
        'NSHumanReadableCopyright': u"Copyright 2019, Kim Jack, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
