"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['save_clipboard.py']
DATA_FILES = ['clipboard_history.txt']
OPTIONS = {
	'iconfile': 'ClipboardSaver.icns',
	'plist': {
        'CFBundleName': "ClipboardSaver",
        'CFBundleDisplayName': "ClipboardSaver",
        'CFBundleGetInfoString': "ClipboardSaver",
        'CFBundleIdentifier': "com.metachris.osx.clipboardsaver",
        'CFBundleVersion': "0.1.0.5",
        'CFBundleShortVersionString': "0.1.0.5",
        'NSHumanReadableCopyright': u"Copyright 2019, Kim Jack, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
