"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['WebHoster.py']
DATA_FILES = [

                # ------------ tamplate
                # --- tamplate
                'webhoster.tpl', 'webhoster_2.tpl', 'webhoster_3.tpl', 'webhoster_4.tpl', 'webhoster_5.tpl',
                'webhoster_6.tpl', 'webhoster_7.tpl', 'webhoster_8.tpl', 'webhoster_9.tpl', 'webhoster_10.tpl',
                'webhoster_11.tpl', 'webhoster_12.tpl', 'webhoster_13.tpl', 'webhoster_14.tpl', 'webhoster_15.tpl',
                'webhoster_16.tpl', 'webhoster_17.tpl', 'webhoster_18.tpl', 'webhoster_19.tpl', 'webhoster_20.tpl',
                'webhoster_21.tpl', 'webhoster_22.tpl', 'webhoster_23.tpl', 'webhoster_24.tpl', 'webhoster_25.tpl',
                'webhoster_26.tpl', 'webhoster_27.tpl', 'webhoster_28.tpl', 'webhoster_29.tpl', 'webhoster_30.tpl',
                'webhoster_31.tpl', 'webhoster_32.tpl', 'webhoster_33.tpl', 'webhoster_34.tpl', 'webhoster_35.tpl',
                'webhoster_36.tpl', 'webhoster_37.tpl', 'webhoster_38.tpl', 'webhoster_39.tpl', 'webhoster_40.tpl',
                'webhoster_41.tpl', 'webhoster_42.tpl', 'webhoster_43.tpl', 'webhoster_44.tpl', 'webhoster_45.tpl',
                'webhoster_46.tpl', 'webhoster_47.tpl', 'webhoster_48.tpl', 'webhoster_49.tpl', 'webhoster_50.tpl',
                'webhoster_51.tpl', 'webhoster_52.tpl', 'webhoster_53.tpl', 'webhoster_54.tpl', 'webhoster_55.tpl',
                'webhoster_56.tpl', 'webhoster_57.tpl', 'webhoster_58.tpl', 'webhoster_59.tpl', 'webhoster_60.tpl',
                'webhoster_61.tpl', 'webhoster_62.tpl', 'webhoster_63.tpl', 'webhoster_64.tpl', 'webhoster_65.tpl',
                'webhoster_66.tpl', 'webhoster_67.tpl', 'webhoster_68.tpl', 'webhoster_69.tpl', 'webhoster_70.tpl',
                'webhoster_71.tpl', 'webhoster_72.tpl', 'webhoster_73.tpl', 'webhoster_74.tpl', 'webhoster_75.tpl',
                'webhoster_76.tpl', 'webhoster_77.tpl', 'webhoster_78.tpl', 'webhoster_79.tpl', 'webhoster_80.tpl',
                'webhoster_81.tpl', 'webhoster_82.tpl', 'webhoster_83.tpl', 'webhoster_84.tpl', 'webhoster_85.tpl',
                'webhoster_86.tpl', 'webhoster_87.tpl', 'webhoster_88.tpl', 'webhoster_89.tpl', 'webhoster_90.tpl',
                'webhoster_91.tpl', 'webhoster_92.tpl', 'webhoster_93.tpl', 'webhoster_94.tpl', 'webhoster_95.tpl',
                'webhoster_96.tpl', 'webhoster_97.tpl', 'webhoster_98.tpl', 'webhoster_99.tpl', 'webhoster_100.tpl',


                # ------------ html
                # --- html
                'html_file.html', 'html_file_2.html', 'html_file_3.html', 'html_file_4.html', 'html_file_5.html',
                'html_file_6.html', 'html_file_7.html', 'html_file_8.html', 'html_file_9.html', 'html_file_10.html',
                'html_file_11.html', 'html_file_12.html', 'html_file_13.html', 'html_file_14.html', 'html_file_15.html',
                'html_file_16.html', 'html_file_17.html', 'html_file_18.html', 'html_file_19.html', 'html_file_20.html',
                'html_file_21.html', 'html_file_22.html', 'html_file_23.html', 'html_file_24.html', 'html_file_25.html',
                'html_file_26.html', 'html_file_27.html', 'html_file_28.html', 'html_file_29.html', 'html_file_30.html',
                'html_file_31.html', 'html_file_32.html', 'html_file_33.html', 'html_file_34.html', 'html_file_35.html',
                'html_file_36.html', 'html_file_37.html', 'html_file_38.html', 'html_file_39.html', 'html_file_40.html',
                'html_file_41.html', 'html_file_42.html', 'html_file_43.html', 'html_file_44.html', 'html_file_45.html',
                'html_file_46.html', 'html_file_47.html', 'html_file_48.html', 'html_file_49.html', 'html_file_50.html',
                'html_file_51.html', 'html_file_52.html', 'html_file_53.html', 'html_file_54.html', 'html_file_55.html',
                'html_file_56.html', 'html_file_57.html', 'html_file_58.html', 'html_file_59.html', 'html_file_60.html',
                'html_file_61.html', 'html_file_62.html', 'html_file_63.html', 'html_file_64.html', 'html_file_65.html',
                'html_file_66.html', 'html_file_67.html', 'html_file_68.html', 'html_file_69.html', 'html_file_70.html',
                'html_file_71.html', 'html_file_72.html', 'html_file_73.html', 'html_file_74.html', 'html_file_75.html',
                'html_file_76.html', 'html_file_77.html', 'html_file_78.html', 'html_file_79.html', 'html_file_80.html',
                'html_file_81.html', 'html_file_82.html', 'html_file_83.html', 'html_file_84.html', 'html_file_85.html',
                'html_file_86.html', 'html_file_87.html', 'html_file_88.html', 'html_file_89.html', 'html_file_90.html',
                'html_file_91.html', 'html_file_92.html', 'html_file_93.html', 'html_file_94.html', 'html_file_95.html',
                'html_file_96.html', 'html_file_97.html', 'html_file_98.html', 'html_file_99.html', 'html_file_100.html',


                # ------------ Image
                # --- png
                'image.png', 'image_2.png', 'image_3.png', 'image_4.png', 'image_5.png',
                'image_6.png', 'image_7.png', 'image_8.png', 'image_9.png', 'image_10.png',
                'image_11.png', 'image_12.png', 'image_13.png', 'image_14.png', 'image_15.png',
                'image_16.png', 'image_17.png', 'image_18.png', 'image_19.png', 'image_20.png',
                'image_21.png', 'image_22.png', 'image_23.png', 'image_24.png', 'image_25.png',
                'image_26.png', 'image_27.png', 'image_28.png', 'image_29.png', 'image_30.png',
                'image_31.png', 'image_32.png', 'image_33.png', 'image_34.png', 'image_35.png',
                'image_36.png', 'image_37.png', 'image_38.png', 'image_39.png', 'image_40.png',
                'image_41.png', 'image_42.png', 'image_43.png', 'image_44.png', 'image_45.png',
                'image_46.png', 'image_47.png', 'image_48.png', 'image_49.png', 'image_50.png',
                'image_51.png', 'image_52.png', 'image_53.png', 'image_54.png', 'image_55.png',
                'image_56.png', 'image_57.png', 'image_58.png', 'image_59.png', 'image_60.png',
                'image_61.png', 'image_62.png', 'image_63.png', 'image_64.png', 'image_65.png',
                'image_66.png', 'image_67.png', 'image_68.png', 'image_69.png', 'image_70.png',
                'image_71.png', 'image_72.png', 'image_73.png', 'image_74.png', 'image_75.png',
                'image_76.png', 'image_77.png', 'image_78.png', 'image_79.png', 'image_80.png',
                'image_81.png', 'image_82.png', 'image_83.png', 'image_84.png', 'image_85.png',
                'image_86.png', 'image_87.png', 'image_88.png', 'image_89.png', 'image_90.png',
                'image_91.png', 'image_92.png', 'image_93.png', 'image_94.png', 'image_95.png',
                'image_96.png', 'image_97.png', 'image_98.png', 'image_99.png', 'image_100.png',

                # --- gif
                'gif_file.gif', 'gif_file_2.gif', 'gif_file_3.gif', 'gif_file_4.gif', 'gif_file_5.gif',
                'gif_file_6.gif', 'gif_file_7.gif', 'gif_file_8.gif', 'gif_file_9.gif', 'gif_file_10.gif',
                'gif_file_11.gif', 'gif_file_12.gif', 'gif_file_13.gif', 'gif_file_14.gif', 'gif_file_15.gif',
                'gif_file_16.gif', 'gif_file_17.gif', 'gif_file_18.gif', 'gif_file_19.gif', 'gif_file_20.gif',
                'gif_file_21.gif', 'gif_file_22.gif', 'gif_file_23.gif', 'gif_file_24.gif', 'gif_file_25.gif',
                'gif_file_26.gif', 'gif_file_27.gif', 'gif_file_28.gif', 'gif_file_29.gif', 'gif_file_30.gif',
                'gif_file_31.gif', 'gif_file_32.gif', 'gif_file_33.gif', 'gif_file_34.gif', 'gif_file_35.gif',
                'gif_file_36.gif', 'gif_file_37.gif', 'gif_file_38.gif', 'gif_file_39.gif', 'gif_file_40.gif',
                'gif_file_41.gif', 'gif_file_42.gif', 'gif_file_43.gif', 'gif_file_44.gif', 'gif_file_45.gif',
                'gif_file_46.gif', 'gif_file_47.gif', 'gif_file_48.gif', 'gif_file_49.gif', 'gif_file_50.gif',
                'gif_file_51.gif', 'gif_file_52.gif', 'gif_file_53.gif', 'gif_file_54.gif', 'gif_file_55.gif',
                'gif_file_56.gif', 'gif_file_57.gif', 'gif_file_58.gif', 'gif_file_59.gif', 'gif_file_60.gif',
                'gif_file_61.gif', 'gif_file_62.gif', 'gif_file_63.gif', 'gif_file_64.gif', 'gif_file_65.gif',
                'gif_file_66.gif', 'gif_file_67.gif', 'gif_file_68.gif', 'gif_file_69.gif', 'gif_file_70.gif',
                'gif_file_71.gif', 'gif_file_72.gif', 'gif_file_73.gif', 'gif_file_74.gif', 'gif_file_75.gif',
                'gif_file_76.gif', 'gif_file_77.gif', 'gif_file_78.gif', 'gif_file_79.gif', 'gif_file_80.gif',
                'gif_file_81.gif', 'gif_file_82.gif', 'gif_file_83.gif', 'gif_file_84.gif', 'gif_file_85.gif',
                'gif_file_86.gif', 'gif_file_87.gif', 'gif_file_88.gif', 'gif_file_89.gif', 'gif_file_90.gif',
                'gif_file_91.gif', 'gif_file_92.gif', 'gif_file_93.gif', 'gif_file_94.gif', 'gif_file_95.gif',
                'gif_file_96.gif', 'gif_file_97.gif', 'gif_file_98.gif', 'gif_file_99.gif', 'gif_file_100.gif',


                # ------------ Image
                # --- css
                'style.css', 'style_2.css', 'style_3.css', 'style_4.css', 'style_5.css',
                'style_6.css', 'style_7.css', 'style_8.css', 'style_9.css', 'style_10.css',
                'style_11.css', 'style_12.css', 'style_13.css', 'style_14.css', 'style_15.css',
                'style_16.css', 'style_17.css', 'style_18.css', 'style_19.css', 'style_20.css',
                'style_21.css', 'style_22.css', 'style_23.css', 'style_24.css', 'style_25.css',
                'style_26.css', 'style_27.css', 'style_28.css', 'style_29.css', 'style_30.css',
                'style_31.css', 'style_32.css', 'style_33.css', 'style_34.css', 'style_35.css',
                'style_36.css', 'style_37.css', 'style_38.css', 'style_39.css', 'style_40.css',
                'style_41.css', 'style_42.css', 'style_43.css', 'style_44.css', 'style_45.css',
                'style_46.css', 'style_47.css', 'style_48.css', 'style_49.css', 'style_50.css',
                'style_51.css', 'style_52.css', 'style_53.css', 'style_54.css', 'style_55.css',
                'style_56.css', 'style_57.css', 'style_58.css', 'style_59.css', 'style_60.css',
                'style_61.css', 'style_62.css', 'style_63.css', 'style_64.css', 'style_65.css',
                'style_66.css', 'style_67.css', 'style_68.css', 'style_69.css', 'style_70.css',
                'style_71.css', 'style_72.css', 'style_73.css', 'style_74.css', 'style_75.css',
                'style_76.css', 'style_77.css', 'style_78.css', 'style_79.css', 'style_80.css',
                'style_81.css', 'style_82.css', 'style_83.css', 'style_84.css', 'style_85.css',
                'style_86.css', 'style_87.css', 'style_88.css', 'style_89.css', 'style_90.css',
                'style_91.css', 'style_92.css', 'style_93.css', 'style_94.css', 'style_95.css',
                'style_96.css', 'style_97.css', 'style_98.css', 'style_99.css', 'style_100.css',


                # ------------ programming language
                # --- py
                'py_file.py', 'py_file_2.py', 'py_file_3.py', 'py_file_4.py', 'py_file_5.py',
                'py_file_6.py', 'py_file_7.py', 'py_file_8.py', 'py_file_9.py', 'py_file_10.py',
                'py_file_11.py', 'py_file_12.py', 'py_file_13.py', 'py_file_14.py', 'py_file_15.py',
                'py_file_16.py', 'py_file_17.py', 'py_file_18.py', 'py_file_19.py', 'py_file_20.py',
                'py_file_21.py', 'py_file_22.py', 'py_file_23.py', 'py_file_24.py', 'py_file_25.py',
                'py_file_26.py', 'py_file_27.py', 'py_file_28.py', 'py_file_29.py', 'py_file_30.py',
                'py_file_31.py', 'py_file_32.py', 'py_file_33.py', 'py_file_34.py', 'py_file_35.py',
                'py_file_36.py', 'py_file_37.py', 'py_file_38.py', 'py_file_39.py', 'py_file_40.py',
                'py_file_41.py', 'py_file_42.py', 'py_file_43.py', 'py_file_44.py', 'py_file_45.py',
                'py_file_46.py', 'py_file_47.py', 'py_file_48.py', 'py_file_49.py', 'py_file_50.py',
                'py_file_51.py', 'py_file_52.py', 'py_file_53.py', 'py_file_54.py', 'py_file_55.py',
                'py_file_56.py', 'py_file_57.py', 'py_file_58.py', 'py_file_59.py', 'py_file_60.py',
                'py_file_61.py', 'py_file_62.py', 'py_file_63.py', 'py_file_64.py', 'py_file_65.py',
                'py_file_66.py', 'py_file_67.py', 'py_file_68.py', 'py_file_69.py', 'py_file_70.py',
                'py_file_71.py', 'py_file_72.py', 'py_file_73.py', 'py_file_74.py', 'py_file_75.py',
                'py_file_76.py', 'py_file_77.py', 'py_file_78.py', 'py_file_79.py', 'py_file_80.py',
                'py_file_81.py', 'py_file_82.py', 'py_file_83.py', 'py_file_84.py', 'py_file_85.py',
                'py_file_86.py', 'py_file_87.py', 'py_file_88.py', 'py_file_89.py', 'py_file_90.py',
                'py_file_91.py', 'py_file_92.py', 'py_file_93.py', 'py_file_94.py', 'py_file_95.py',
                'py_file_96.py', 'py_file_97.py', 'py_file_98.py', 'py_file_99.py', 'py_file_100.py',

                # --- js
                'js_file.js', 'js_file_2.js', 'js_file_3.js', 'js_file_4.js', 'js_file_5.js',
                'js_file_6.js', 'js_file_7.js', 'js_file_8.js', 'js_file_9.js', 'js_file_10.js',
                'js_file_11.js', 'js_file_12.js', 'js_file_13.js', 'js_file_14.js', 'js_file_15.js',
                'js_file_16.js', 'js_file_17.js', 'js_file_18.js', 'js_file_19.js', 'js_file_20.js',
                'js_file_21.js', 'js_file_22.js', 'js_file_23.js', 'js_file_24.js', 'js_file_25.js',
                'js_file_26.js', 'js_file_27.js', 'js_file_28.js', 'js_file_29.js', 'js_file_30.js',
                'js_file_31.js', 'js_file_32.js', 'js_file_33.js', 'js_file_34.js', 'js_file_35.js',
                'js_file_36.js', 'js_file_37.js', 'js_file_38.js', 'js_file_39.js', 'js_file_40.js',
                'js_file_41.js', 'js_file_42.js', 'js_file_43.js', 'js_file_44.js', 'js_file_45.js',
                'js_file_46.js', 'js_file_47.js', 'js_file_48.js', 'js_file_49.js', 'js_file_50.js',
                'js_file_51.js', 'js_file_52.js', 'js_file_53.js', 'js_file_54.js', 'js_file_55.js',
                'js_file_56.js', 'js_file_57.js', 'js_file_58.js', 'js_file_59.js', 'js_file_60.js',
                'js_file_61.js', 'js_file_62.js', 'js_file_63.js', 'js_file_64.js', 'js_file_65.js',
                'js_file_66.js', 'js_file_67.js', 'js_file_68.js', 'js_file_69.js', 'js_file_70.js',
                'js_file_71.js', 'js_file_72.js', 'js_file_73.js', 'js_file_74.js', 'js_file_75.js',
                'js_file_76.js', 'js_file_77.js', 'js_file_78.js', 'js_file_79.js', 'js_file_80.js',
                'js_file_81.js', 'js_file_82.js', 'js_file_83.js', 'js_file_84.js', 'js_file_85.js',
                'js_file_86.js', 'js_file_87.js', 'js_file_88.js', 'js_file_89.js', 'js_file_90.js',
                'js_file_91.js', 'js_file_92.js', 'js_file_93.js', 'js_file_94.js', 'js_file_95.js',
                'js_file_96.js', 'js_file_97.js', 'js_file_98.js', 'js_file_99.js', 'js_file_100.js',

                # --- php
                'php_file.php', 'php_file_2.php', 'php_file_3.php', 'php_file_4.php', 'php_file_5.php',
                'php_file_6.php', 'php_file_7.php', 'php_file_8.php', 'php_file_9.php', 'php_file_10.php',
                'php_file_11.php', 'php_file_12.php', 'php_file_13.php', 'php_file_14.php', 'php_file_15.php',
                'php_file_16.php', 'php_file_17.php', 'php_file_18.php', 'php_file_19.php', 'php_file_20.php',
                'php_file_21.php', 'php_file_22.php', 'php_file_23.php', 'php_file_24.php', 'php_file_25.php',
                'php_file_26.php', 'php_file_27.php', 'php_file_28.php', 'php_file_29.php', 'php_file_30.php',
                'php_file_31.php', 'php_file_32.php', 'php_file_33.php', 'php_file_34.php', 'php_file_35.php',
                'php_file_36.php', 'php_file_37.php', 'php_file_38.php', 'php_file_39.php', 'php_file_40.php',
                'php_file_41.php', 'php_file_42.php', 'php_file_43.php', 'php_file_44.php', 'php_file_45.php',
                'php_file_46.php', 'php_file_47.php', 'php_file_48.php', 'php_file_49.php', 'php_file_50.php',
                'php_file_51.php', 'php_file_52.php', 'php_file_53.php', 'php_file_54.php', 'php_file_55.php',
                'php_file_56.php', 'php_file_57.php', 'php_file_58.php', 'php_file_59.php', 'php_file_60.php',
                'php_file_61.php', 'php_file_62.php', 'php_file_63.php', 'php_file_64.php', 'php_file_65.php',
                'php_file_66.php', 'php_file_67.php', 'php_file_68.php', 'php_file_69.php', 'php_file_70.php',
                'php_file_71.php', 'php_file_72.php', 'php_file_73.php', 'php_file_74.php', 'php_file_75.php',
                'php_file_76.php', 'php_file_77.php', 'php_file_78.php', 'php_file_79.php', 'php_file_80.php',
                'php_file_81.php', 'php_file_82.php', 'php_file_83.php', 'php_file_84.php', 'php_file_85.php',
                'php_file_86.php', 'php_file_87.php', 'php_file_88.php', 'php_file_89.php', 'php_file_90.php',
                'php_file_91.php', 'php_file_92.php', 'php_file_93.php', 'php_file_94.php', 'php_file_95.php',
                'php_file_96.php', 'php_file_97.php', 'php_file_98.php', 'php_file_99.php', 'php_file_100.php',



                # ------------ document file
                # --- txt
                'txt_file.txt', 'txt_file_2.txt', 'txt_file_3.txt', 'txt_file_4.txt', 'txt_file_5.txt',
                'txt_file_6.txt', 'txt_file_7.txt', 'txt_file_8.txt', 'txt_file_9.txt', 'txt_file_10.txt',
                'txt_file_11.txt', 'txt_file_12.txt', 'txt_file_13.txt', 'txt_file_14.txt', 'txt_file_15.txt',
                'txt_file_16.txt', 'txt_file_17.txt', 'txt_file_18.txt', 'txt_file_19.txt', 'txt_file_20.txt',
                'txt_file_21.txt', 'txt_file_22.txt', 'txt_file_23.txt', 'txt_file_24.txt', 'txt_file_25.txt',
                'txt_file_26.txt', 'txt_file_27.txt', 'txt_file_28.txt', 'txt_file_29.txt', 'txt_file_30.txt',
                'txt_file_31.txt', 'txt_file_32.txt', 'txt_file_33.txt', 'txt_file_34.txt', 'txt_file_35.txt',
                'txt_file_36.txt', 'txt_file_37.txt', 'txt_file_38.txt', 'txt_file_39.txt', 'txt_file_40.txt',
                'txt_file_41.txt', 'txt_file_42.txt', 'txt_file_43.txt', 'txt_file_44.txt', 'txt_file_45.txt',
                'txt_file_46.txt', 'txt_file_47.txt', 'txt_file_48.txt', 'txt_file_49.txt', 'txt_file_50.txt',
                'txt_file_51.txt', 'txt_file_52.txt', 'txt_file_53.txt', 'txt_file_54.txt', 'txt_file_55.txt',
                'txt_file_56.txt', 'txt_file_57.txt', 'txt_file_58.txt', 'txt_file_59.txt', 'txt_file_60.txt',
                'txt_file_61.txt', 'txt_file_62.txt', 'txt_file_63.txt', 'txt_file_64.txt', 'txt_file_65.txt',
                'txt_file_66.txt', 'txt_file_67.txt', 'txt_file_68.txt', 'txt_file_69.txt', 'txt_file_70.txt',
                'txt_file_71.txt', 'txt_file_72.txt', 'txt_file_73.txt', 'txt_file_74.txt', 'txt_file_75.txt',
                'txt_file_76.txt', 'txt_file_77.txt', 'txt_file_78.txt', 'txt_file_79.txt', 'txt_file_80.txt',
                'txt_file_81.txt', 'txt_file_82.txt', 'txt_file_83.txt', 'txt_file_84.txt', 'txt_file_85.txt',
                'txt_file_86.txt', 'txt_file_87.txt', 'txt_file_88.txt', 'txt_file_89.txt', 'txt_file_90.txt',
                'txt_file_91.txt', 'txt_file_92.txt', 'txt_file_93.txt', 'txt_file_94.txt', 'txt_file_95.txt',
                'txt_file_96.txt', 'txt_file_97.txt', 'txt_file_98.txt', 'txt_file_99.txt', 'txt_file_100.txt',

                # --- pdf
                'pdf_file.pdf', 'pdf_file_2.pdf', 'pdf_file_3.pdf', 'pdf_file_4.pdf', 'pdf_file_5.pdf',
                'pdf_file_6.pdf', 'pdf_file_7.pdf', 'pdf_file_8.pdf', 'pdf_file_9.pdf', 'pdf_file_10.pdf',
                'pdf_file_11.pdf', 'pdf_file_12.pdf', 'pdf_file_13.pdf', 'pdf_file_14.pdf', 'pdf_file_15.pdf',
                'pdf_file_16.pdf', 'pdf_file_17.pdf', 'pdf_file_18.pdf', 'pdf_file_19.pdf', 'pdf_file_20.pdf',
                'pdf_file_21.pdf', 'pdf_file_22.pdf', 'pdf_file_23.pdf', 'pdf_file_24.pdf', 'pdf_file_25.pdf',
                'pdf_file_26.pdf', 'pdf_file_27.pdf', 'pdf_file_28.pdf', 'pdf_file_29.pdf', 'pdf_file_30.pdf',
                'pdf_file_31.pdf', 'pdf_file_32.pdf', 'pdf_file_33.pdf', 'pdf_file_34.pdf', 'pdf_file_35.pdf',
                'pdf_file_36.pdf', 'pdf_file_37.pdf', 'pdf_file_38.pdf', 'pdf_file_39.pdf', 'pdf_file_40.pdf',
                'pdf_file_41.pdf', 'pdf_file_42.pdf', 'pdf_file_43.pdf', 'pdf_file_44.pdf', 'pdf_file_45.pdf',
                'pdf_file_46.pdf', 'pdf_file_47.pdf', 'pdf_file_48.pdf', 'pdf_file_49.pdf', 'pdf_file_50.pdf',
                'pdf_file_51.pdf', 'pdf_file_52.pdf', 'pdf_file_53.pdf', 'pdf_file_54.pdf', 'pdf_file_55.pdf',
                'pdf_file_56.pdf', 'pdf_file_57.pdf', 'pdf_file_58.pdf', 'pdf_file_59.pdf', 'pdf_file_60.pdf',
                'pdf_file_61.pdf', 'pdf_file_62.pdf', 'pdf_file_63.pdf', 'pdf_file_64.pdf', 'pdf_file_65.pdf',
                'pdf_file_66.pdf', 'pdf_file_67.pdf', 'pdf_file_68.pdf', 'pdf_file_69.pdf', 'pdf_file_70.pdf',
                'pdf_file_71.pdf', 'pdf_file_72.pdf', 'pdf_file_73.pdf', 'pdf_file_74.pdf', 'pdf_file_75.pdf',
                'pdf_file_76.pdf', 'pdf_file_77.pdf', 'pdf_file_78.pdf', 'pdf_file_79.pdf', 'pdf_file_80.pdf',
                'pdf_file_81.pdf', 'pdf_file_82.pdf', 'pdf_file_83.pdf', 'pdf_file_84.pdf', 'pdf_file_85.pdf',
                'pdf_file_86.pdf', 'pdf_file_87.pdf', 'pdf_file_88.pdf', 'pdf_file_89.pdf', 'pdf_file_90.pdf',
                'pdf_file_91.pdf', 'pdf_file_92.pdf', 'pdf_file_93.pdf', 'pdf_file_94.pdf', 'pdf_file_95.pdf',
                'pdf_file_96.pdf', 'pdf_file_97.pdf', 'pdf_file_98.pdf', 'pdf_file_99.pdf', 'pdf_file_100.pdf',

            ]



OPTIONS = {
	'iconfile': 'webhoster.icns',
	'plist': {
        'CFBundleName': "WebHoster",
        'CFBundleDisplayName': "WebHoster",
        'CFBundleGetInfoString': "WebHoster",
        'CFBundleIdentifier': "com.metachris.osx.WebHoster",
        'CFBundleVersion': "0.1.0.4",
        'CFBundleShortVersionString': "0.1.0.4",
        'CFBundleShortVersionString': "0.1.0.4",
        'port': "1977",
        'NSHumanReadableCopyright': u"Copyright 2019, Kim Jack, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
